<a href="https://colab.research.google.com/github/AhmedElsayed201097/Tensorflow-basics/blob/master/TensorFlowComponents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
"""
tensorflow component 
1.3.1		Session
1.3.2		Constants
1.3.3		Variables
1.3.4		Placeholders
1.3.5		Operations
1.3.6		Graph
1.3.7		Eager Execution
"""

In [0]:
# 1.3.1) Session

In [0]:
import tensorflow as tf 
import numpy as np 

In [0]:
# first way to use session 
sess =  tf.Session()   # used to define session 
sess.run()  # used to run on operation of session 
sess.close() # used to close session 

In [0]:
# example 1
sess =  tf.Session()
b = tf.constant(5)
print(sess.run(b))



5


In [0]:
# example 2
sess= tf.Session()
a=tf.constant(12)
b=tf.constant(14)
print (sess.run(a+4)+12)   #  we can +,-,*,/ to any constatnt 
print(sess.run(b))

28
14


In [0]:
# the second way of defining session 
c=tf.constant(45)
with tf.Session() as sess:     # using session as block any instruction should be run like c
  print(sess.run(c))

45


In [0]:
#1.3.2) Constant   is something can't be modifyied

In [0]:
c= tf.constant(value,dtype)      # value can be number (integer ,float),string,list      dtype is the type of constant and its optional


In [0]:
#example 1
a = tf.constant(3)
b = tf.constant(3,tf.float32)    #### defining float 
c = tf.constant([2,5,6,9,6])
d = tf.constant([[2,5,6],
                 [8,5,8],
                 [8,8,1]])
e = tf.constant('I love TensorFlow')
with tf.Session() as sess : 
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))




3
3.0
[2 5 6 9 6]
[[2 5 6]
 [8 5 8]
 [8 8 1]]
b'I love TensorFlow'


In [0]:
#1.3.3) Variable   something can be modified,used with something will be changed during code like w,b 
v=tf.Variable(value,dtype) # to define variable 
tf.global_variables_initializer()  # must be used before runing any variable

In [0]:
a = tf.Variable(3)
b = tf.Variable(3,tf.float32)
c = tf.Variable([2,5,6,9,6])
d = tf.Variable([[2,5,6],[8,5,8], [8,8,1]])
e = tf.Variable('I love TensorFlow')
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())     
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))


3
3
[2 5 6 9 6]
[[2 5 6]
 [8 5 8]
 [8 8 1]]
b'I love TensorFlow'


In [0]:
price = tf.Variable(20) 
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print('original price is : ',sess.run(price))


original price is :  20


In [0]:
x=tf.Variable(45)
init=tf.global_variables_initializer()
s=tf.Session()
sess.run(init)
print(sess.run(x))

45


In [0]:
# to modify variable values you have two ways 
#first  redefine variable with anthor value

In [0]:
price = tf.Variable(30) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(40) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(50) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(60) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))


the price is :  30
the price is :  40
the price is :  50
the price is :  60


In [0]:
# the second way use : tf.assign(value,newvalue)
price = tf.assign(price,50)
print('new price is : ',sess.run(price))


new price is :  50


In [0]:
for j in range(6):
  price=tf.assign(price,price+j)
  print('new price is : ',sess.run(price))

new price is :  457
new price is :  458
new price is :  460
new price is :  463
new price is :  467
new price is :  472


In [0]:
#1.3.4) Placeholder  used to hold a memory sapce for something will be initialize in the run    using feed_dict : {placeholder: value }
a=tf.placeholder(tf.float32)
with tf.Session() as tf :
  print(sess.run(a,feed_dict={a:4}))

4.0


In [0]:
# we always use it to define vars of the equation   like r=a**2
import tensorflow as tf 
a = tf.placeholder(tf.float32)
b = a*2
with tf.Session() as sess : 
    result = sess.run(b , feed_dict ={a:3})
    print(result)


6.0


In [0]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = tf.placeholder(tf.float32)
w = tf.placeholder(tf.float32)
b = x*2 + 3*y**4 - 4/z + w-9
with tf.Session() as sess : 
    result = sess.run(b , feed_dict ={x:3,y:4,z:8,w:6})
    print(result)




770.5


In [0]:
# using const with placeholder
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = tf.constant(8,tf.float32)
w = tf.constant(6,tf.float32)

b = x*2 + 3*y**4 - 4/z + w-9

with tf.Session() as sess :
    result = sess.run(b , feed_dict ={x:3.0,y:4.0})
    print(result)


770.5


In [0]:
x = tf.placeholder(tf.float32)
y = x**2
with tf.Session() as sess :
    print(sess.run(y,feed_dict={x:5}))


25.0


In [0]:
# placeholder can take list of values     and this what we need in ml and dl as x,y is the data always be a file of data like a list and we send to the equation 
x=tf.placeholder(tf.float32)
a=x**2
with tf.Session( ) as sess:
  result=sess.run(a,feed_dict={x:[1,2,3,4]})
  print(result)

[ 1.  4.  9. 16.]


In [0]:
#w*x + b

w = tf.constant([5.0])
b = tf.Variable([7.0],tf.float32)

x = tf.placeholder(tf.float32)

LinearRegressionModel = w*x + b

with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    print(sess.run(LinearRegressionModel,{x:[3,5,7,9]}))



[22. 32. 42. 52.]


In [0]:
#1.3.5) Operations
tf.add()
tf.subtract()
tf.multiply()
etc ...................

In [0]:
# add to strings
s1 = tf.constant('hi ')
s2 = tf.constant('people ')
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))


b'hi people '


In [0]:
# add to numbers 
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))



50


In [0]:
d=tf.constant(12)
f=tf.constant(14)
s=tf.add(d,f)
sess=tf.Session()
print(sess.run(s))

26


In [0]:
#mul to numbers
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.multiply(s1,s2)

sess = tf.Session()
print(sess.run(s3))


600


In [0]:
# sub to numbers
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.subtract(s1,s2)

sess = tf.Session()
print(sess.run(s3))


-10


In [0]:
# div to number
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.divide(s1,s2)

sess = tf.Session()
print(sess.run(s3))


0.6666666666666666


In [0]:
#power 
s1 = tf.constant(20)
s2 = tf.constant(3)
s3 = tf.pow(s1,s2)

sess = tf.Session()
print(sess.run(s3))


8000


In [0]:
# add 2 matrixs with the same shape
s1 = tf.constant([5,6,7,8])
s2 = tf.constant([1,2,3,4])
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))


[ 6  8 10 12]


In [0]:
# matrix mul wit (n*m    *** m* l)
matrix1 = tf.constant([[5., 3.]])
matrix2 = tf.constant([[2.],
                       [2.]])
product = tf.matmul(matrix1, matrix2)


with tf.Session() as sess:
    result = sess.run(product)
    print (result)



[[16.]]


In [0]:
# transopse of matrix matrix_trancepose
matrix1 = tf.constant([[5,6,9,8],
                      [1,2,8,9],
                      [7,9,5,6],
                      [1,2,3,9]])


matrix2 = tf.matrix_transpose(matrix1)

with tf.Session() as sess:
    result = sess.run(matrix2)
    print (result)


[[5 1 7 1]
 [6 2 9 2]
 [9 8 5 3]
 [8 9 6 9]]


In [0]:
#1.3.6) Graph  is the place we have edges and nodes we can define to use when we need to knoow our operations (constant,var,place),arthimetic operations and so on
graph = tf.get_default_graph()   # used to define graph
graph.get_operations()      # used to get operation done in the graph

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Const_4' type=Const>,
 <tf.Operation 'add/y' type=Const>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'Const_5' type=Const>,
 <tf.Operation 'Const_6' type=Const>,
 <tf.Operation 'add_1/y' type=Const>,
 <tf.Operation 'add_1' type=AddV2>,
 <tf.Operation 'Const_7' type=Const>,
 <tf.Operation 'Const_8' type=Const>,
 <tf.Operation 'Const_9' type=Const>,
 <tf.Operation 'Const_10' type=Const>,
 <tf.Operation 'Const_11' type=Const>,
 <tf.Operation 'Const_12' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Vari

In [0]:

a= tf.constant(5)
graph.get_operations()
c= tf.add(a,b)
graph.get_operations()
d= tf.placeholder(tf.float32)
graph.get_operations()
e= tf.Variable(2)
graph.get_operations



TypeError: ignored

In [0]:

for operation in graph.get_operations() :
    print(operation.name)


Const
Const_1
Const_2
Const_3
Const_4
add/y
add
Const_5
Const_6
add_1/y
add_1
Const_7
Const_8
Const_9
Const_10
Const_11
Const_12
Variable/initial_value
Variable
Variable/Assign
Variable/read
Variable_1/initial_value
Variable_1
Variable_1/Assign
Variable_1/read
Variable_2/initial_value
Variable_2
Variable_2/Assign
Variable_2/read
Variable_3/initial_value
Variable_3
Variable_3/Assign
Variable_3/read
Variable_4/initial_value
Variable_4
Variable_4/Assign
Variable_4/read
Variable_5/initial_value
Variable_5
Variable_5/Assign
Variable_5/read
Variable_6/initial_value
Variable_6
Variable_6/Assign
Variable_6/read
Variable_7/initial_value
Variable_7
Variable_7/Assign
Variable_7/read
Variable_8/initial_value
Variable_8
Variable_8/Assign
Variable_8/read
Variable_9/initial_value
Variable_9
Variable_9/Assign
Variable_9/read
init
Variable_10/initial_value
Variable_10
Variable_10/Assign
Variable_10/read
init_1
Variable_11/initial_value
Variable_11
Variable_11/Assign
Variable_11/read
init_2
Variable_12/

In [46]:
# 1.3.7) Eager Execution  is used to stop session thinking we can use tensorflow without any session 
import tensorflow as tf
tf.enable_eager_execution()      ### must be used in new notebook


ValueError: ignored